export const ALL_CUSTOMER_REQUEST = "ALL_CUSTOMER_REQUEST"
export const ALL_CUSTOMER_SUCCESS = "ALL_CUSTOMER_SUCCESS"
export const ALL_CUSTOMER_FAIL = "ALL_CUSTOMER_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST"
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS"
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL"

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAIL = "GET_ORDER_FAIL"

export const ADD_CUSTOMER_REQUEST = "ADD_CUSTOMER_REQUEST"
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS"
export const ADD_CUSTOMER_FAIL = "ADD_CUSTOMER_FAIL"

export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS"
export const UPDATE_CUSTOMER_REQUEST = "UPDATE_CUSTOMER_REQUEST"
export const UPDATE_CUSTOMER_FAIL = "UPDATE_CUSTOMER_FAIL"